using System.Numerics;
using System.Text;

namespace TerrainGen.Output;

/// <summary>
/// Emits the optional preview scene (<c>--with-cameras</c>): a complete master
/// scene that imports the terrain template and supplies a seasonal sky, a
/// fill light, and five framed cameras (wide / aerial / ground / sunrise /
/// topdown). Camera positions adapt to the actual world-space peak so the
/// terrain stays framed regardless of <c>--size</c>.
///
/// We generate the preview at <c>scenes/&lt;name&gt;-preview.yaml</c> rather than
/// inside <c>scenes/libraries/terrain/</c> so that the imported template's
/// internal asset paths (relative to its own directory) keep resolving and
/// the master-scene camera/sky overrides land at the top of the YAML tree.
/// </summary>
public static class PreviewSceneEmitter
{
    /// <param name="hMax">World-space peak height of the terrain (= <c>heightScale</c>).</param>
    /// <param name="hAvg">World-space mean height of the terrain.</param>
    public static string Write(GenerationConfig cfg, string templateName, float hMax, float hAvg)
    {
        var sky = PaletteLibrary.SkyFor(cfg.Season);
        float size = cfg.Size;

        var sb = new StringBuilder();
        sb.AppendLine("# 3D-Ray terrain preview scene — generated by TerrainGen --with-cameras");
        sb.AppendLine("#");
        sb.AppendLine("# Render with:");
        sb.AppendLine($"#   dotnet run --project src/RayTracer/RayTracer.csproj -c Release -- \\");
        sb.AppendLine($"#     -i scenes/{cfg.Name}-preview.yaml -o renders/preview-{cfg.Name}.png \\");
        sb.AppendLine("#     -w 1280 -H 720 -s 256 -d 6 -S 2 -c wide");
        sb.AppendLine("#");
        sb.AppendLine("# Cameras: wide | aerial | ground | sunrise | topdown");
        sb.AppendLine("# List them with --list-cameras.");
        sb.AppendLine();

        sb.AppendLine("imports:");
        sb.AppendLine($"  - path: \"libraries/terrain/{cfg.Name}.yaml\"");
        sb.AppendLine();

        EmitWorld(sb, cfg, sky);
        EmitLights(sb, sky);
        EmitCameras(sb, size, hMax, hAvg);
        EmitEntities(sb, templateName);

        return sb.ToString();
    }

    private static void EmitWorld(StringBuilder sb, GenerationConfig cfg, PaletteLibrary.SkyPalette sky)
    {
        sb.AppendLine("world:");
        sb.AppendLine("  sky:");
        sb.AppendLine("    type: \"gradient\"");
        sb.AppendLine($"    zenith_color:  {YamlEmitter.Vec3(sky.Zenith)}");
        sb.AppendLine($"    horizon_color: {YamlEmitter.Vec3(sky.Horizon)}");
        sb.AppendLine($"    ground_color:  {YamlEmitter.Vec3(sky.Ground)}");
        sb.AppendLine("    sun:");
        sb.AppendLine($"      direction: {YamlEmitter.Vec3(Vector3.Normalize(sky.SunDir))}");
        sb.AppendLine($"      color: {YamlEmitter.Vec3(sky.SunColor)}");
        sb.AppendLine($"      intensity: {YamlEmitter.F(sky.SunIntensity)}");
        sb.AppendLine($"      size: {YamlEmitter.F(sky.SunSize)}");
        sb.AppendLine($"      falloff: 32.0");

        // Light atmospheric haze when sea is present (aerial perspective).
        if (cfg.HasFlag(WaterFeatures.Mare))
        {
            sb.AppendLine("  medium:");
            sb.AppendLine("    type: \"height_fog\"");
            sb.AppendLine("    sigma_a: [0.001, 0.001, 0.0012]");
            sb.AppendLine("    sigma_s: [0.010, 0.012, 0.016]");
            sb.AppendLine("    y0: 0.0");
            sb.AppendLine($"    scale_height: {YamlEmitter.F(cfg.Size * 0.05f)}");
            sb.AppendLine("    phase: \"hg\"");
            sb.AppendLine("    g: 0.6");
        }
        sb.AppendLine();
    }

    private static void EmitLights(StringBuilder sb, PaletteLibrary.SkyPalette sky)
    {
        sb.AppendLine("lights:");
        sb.AppendLine("  - type: \"directional\"");
        Vector3 fill = Vector3.Normalize(new Vector3(-sky.SunDir.X, sky.SunDir.Y * 0.5f, -sky.SunDir.Z));
        sb.AppendLine($"    direction: {YamlEmitter.Vec3(fill)}");
        sb.AppendLine($"    color: {YamlEmitter.Vec3(sky.Horizon)}");
        sb.AppendLine($"    intensity: {YamlEmitter.F(sky.SunIntensity * 0.10f)}");
        sb.AppendLine();
    }

    private static void EmitCameras(StringBuilder sb, float size, float hMax, float hAvg)
    {
        sb.AppendLine("cameras:");

        Camera(sb, "wide",
            position: new Vector3(size * 1.0f, hMax * 1.2f + size * 0.20f, size * 0.9f),
            lookAt:   new Vector3(0f, hAvg, 0f),
            fov: 50f, aperture: 0f, focalDist: 1f);

        Camera(sb, "aerial",
            position: new Vector3(0f, hMax * 2.5f + size * 0.30f, size * 0.9f),
            lookAt:   new Vector3(0f, 0f, 0f),
            fov: 55f, aperture: 0f, focalDist: 1f);

        Camera(sb, "ground",
            position: new Vector3(-size * 0.30f, hAvg + size * 0.04f, size * 0.30f),
            lookAt:   new Vector3(size * 0.30f, hAvg, -size * 0.30f),
            fov: 50f, aperture: 0f, focalDist: 1f);

        Camera(sb, "sunrise",
            position: new Vector3(-size * 0.60f, hAvg + size * 0.06f, -size * 0.10f),
            lookAt:   new Vector3(size * 0.40f, hAvg, size * 0.10f),
            fov: 55f, aperture: 0.05f, focalDist: size * 0.8f);

        Camera(sb, "topdown",
            position: new Vector3(0f, hMax * 4f + size * 0.5f, 0.001f),
            lookAt:   new Vector3(0f, 0f, 0f),
            fov: 70f, aperture: 0f, focalDist: 1f);
    }

    private static void Camera(StringBuilder sb, string name, Vector3 position, Vector3 lookAt,
                               float fov, float aperture, float focalDist)
    {
        sb.AppendLine($"  - name: \"{name}\"");
        sb.AppendLine($"    position: {YamlEmitter.Vec3(position)}");
        sb.AppendLine($"    look_at:  {YamlEmitter.Vec3(lookAt)}");
        sb.AppendLine($"    fov:      {YamlEmitter.F(fov)}");
        sb.AppendLine($"    aperture: {YamlEmitter.F(aperture)}");
        sb.AppendLine($"    focal_dist: {YamlEmitter.F(focalDist)}");
        sb.AppendLine();
    }

    private static void EmitEntities(StringBuilder sb, string templateName)
    {
        sb.AppendLine("entities:");
        sb.AppendLine($"  - name: \"terrain\"");
        sb.AppendLine($"    type: \"instance\"");
        sb.AppendLine($"    template: \"{templateName}\"");
        sb.AppendLine($"    translate: [0.000, 0.000, 0.000]");
    }
}
