using System.Collections.Generic;
using System.Globalization;
using System.Numerics;
using System.Text;
using TerrainGen.Splatting;

namespace TerrainGen.Output;

/// <summary>
/// Emits the importable terrain template YAML: a single <c>heightfield</c>
/// entity inside a reusable <c>templates:</c> entry, plus the materials for
/// every stratum that the runtime selector may pick (sand / ground / rock /
/// snow) and the optional water surface. The heightmap PNG path is emitted
/// relative to the YAML file itself (same directory) — same convention the
/// engine's <c>ImageTexture</c> / <c>HeightmapLoader</c> use for scene-local
/// assets.
/// </summary>
public static class YamlEmitter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Write(
        GenerationConfig cfg,
        IReadOnlyList<StratumClassifier.Band> bands,
        bool waterPresent,
        float heightScale,
        string templateName,
        string materialPrefix,
        string heightmapFileName)
    {
        var sb = new StringBuilder();
        EmitHeader(sb, cfg);
        EmitMaterials(sb, cfg, bands, waterPresent, materialPrefix);
        EmitTemplate(sb, cfg, bands, waterPresent, heightScale,
                     templateName, materialPrefix, heightmapFileName);
        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb, GenerationConfig cfg)
    {
        sb.AppendLine("# 3D-Ray terrain template — generated by TerrainGen");
        sb.AppendLine($"# type={cfg.Type.ToString().ToLowerInvariant()} include={DescribeInclude(cfg)} season={cfg.Season.ToString().ToLowerInvariant()}");
        sb.AppendLine($"# size={F(cfg.Size)} resolution={cfg.Resolution} seed={cfg.Seed}");
        sb.AppendLine("#");
        sb.AppendLine("# To use in a scene, place the scene under scenes/ and import this file:");
        sb.AppendLine("#   imports:");
        sb.AppendLine("#     - path: \"libraries/terrain/" + cfg.Name + ".yaml\"");
        sb.AppendLine("#   entities:");
        sb.AppendLine("#     - { type: \"instance\", template: \"<template-name>\", translate: [0, 0, 0] }");
        sb.AppendLine();
    }

    private static string DescribeInclude(GenerationConfig cfg)
    {
        if (cfg.Include == WaterFeatures.None) return "(none)";
        var parts = new List<string>();
        if (cfg.HasFlag(WaterFeatures.Fiumi)) parts.Add("fiumi");
        if (cfg.HasFlag(WaterFeatures.Laghi)) parts.Add("laghi");
        if (cfg.HasFlag(WaterFeatures.Mare))  parts.Add("mare");
        if (cfg.HasFlag(WaterFeatures.Isole)) parts.Add("isole");
        return string.Join(",", parts);
    }

    private static void EmitMaterials(StringBuilder sb, GenerationConfig cfg,
        IReadOnlyList<StratumClassifier.Band> bands, bool waterPresent, string prefix)
    {
        sb.AppendLine("materials:");

        // De-duplicate strata — every band that appears in the bands list
        // gets a material, and only those (no orphans).
        var emitted = new HashSet<Stratum>();
        foreach (var b in bands)
        {
            if (!emitted.Add(b.Stratum)) continue;
            EmitStratumMaterial(sb, b.Stratum, cfg, $"{prefix}_{b.Stratum.Suffix()}");
        }
        if (waterPresent)
            EmitWaterMaterial(sb, $"{prefix}_water");
    }

    private static void EmitStratumMaterial(StringBuilder sb, Stratum stratum, GenerationConfig cfg, string id)
    {
        var p = PaletteLibrary.ForStratum(stratum, cfg.Season);
        sb.AppendLine($"  - id: \"{id}\"");
        sb.AppendLine($"    type: \"{p.Type}\"");
        if (stratum == Stratum.Snow)
        {
            sb.AppendLine($"    color: {Vec3(p.ColorA)}");
            sb.AppendLine($"    roughness: {F(p.Roughness)}");
            sb.AppendLine($"    metallic: 0.000");
            sb.AppendLine($"    specular: {F(p.Specular)}");
            sb.AppendLine($"    subsurface: {F(p.Subsurface)}");
            sb.AppendLine($"    subsurface_color: {Vec3(p.SubsurfaceColor)}");
        }
        else
        {
            sb.AppendLine($"    texture:");
            sb.AppendLine($"      type: \"noise\"");
            sb.AppendLine($"      scale: {F(p.NoiseScale)}");
            sb.AppendLine($"      noise_strength: {F(p.NoiseStrength)}");
            sb.AppendLine($"      colors: [{Vec3(p.ColorA)}, {Vec3(p.ColorB)}]");
            sb.AppendLine($"      randomize_offset: true");
            if (p.Type == "disney")
            {
                sb.AppendLine($"    roughness: {F(p.Roughness)}");
                sb.AppendLine($"    metallic: 0.000");
                sb.AppendLine($"    specular: {F(p.Specular)}");
            }
        }
        sb.AppendLine();
    }

    private static void EmitWaterMaterial(StringBuilder sb, string id)
    {
        sb.AppendLine($"  - id: \"{id}\"");
        sb.AppendLine($"    type: \"disney\"");
        sb.AppendLine($"    color: [0.850, 0.920, 0.950]");
        sb.AppendLine($"    roughness: 0.080");
        sb.AppendLine($"    metallic: 0.000");
        sb.AppendLine($"    specular: 0.500");
        sb.AppendLine($"    spec_trans: 1.000");
        sb.AppendLine($"    ior: 1.330");
        sb.AppendLine($"    transmission_color: [0.300, 0.550, 0.650]");
        sb.AppendLine($"    transmission_depth: 4.000");
        sb.AppendLine();
    }

    private static void EmitTemplate(StringBuilder sb, GenerationConfig cfg,
        IReadOnlyList<StratumClassifier.Band> bands, bool waterPresent, float heightScale,
        string templateName, string materialPrefix, string heightmapFileName)
    {
        // The terrain footprint is [-half, +half] in XZ — same convention the
        // legacy mesh pipeline used so existing preview cameras keep framing.
        float half = cfg.Size * 0.5f;

        // Fallback material when no band matches at the shading point — the
        // ground stratum is the safe pick (covers the widest altitude range).
        string fallback = $"{materialPrefix}_{Stratum.Ground.Suffix()}";

        sb.AppendLine("templates:");
        sb.AppendLine($"  - name: \"{templateName}\"");
        sb.AppendLine("    children:");
        sb.AppendLine("      - type: \"heightfield\"");
        sb.AppendLine($"        bounds: [{F(-half)}, {F(-half)}, {F(half)}, {F(half)}]");
        sb.AppendLine($"        height_scale: {F(heightScale)}");
        sb.AppendLine($"        heightmap_path: \"{heightmapFileName}\"");

        if (waterPresent)
        {
            float seaY = (cfg.SeaLevel >= 0f ? cfg.SeaLevel : 0.30f) * heightScale;
            sb.AppendLine($"        sea_level: {F(seaY)}");
            sb.AppendLine($"        sea_material: \"{materialPrefix}_water\"");
        }

        sb.AppendLine("        strata:");
        foreach (var b in bands)
        {
            string matId = $"{materialPrefix}_{b.Stratum.Suffix()}";
            sb.AppendLine($"          - {{ min_altitude: {F(b.MinAltitude)}, max_altitude: {F(b.MaxAltitude)}, "
                          + $"min_slope_deg: {F(b.MinSlopeDeg)}, max_slope_deg: {F(b.MaxSlopeDeg)}, "
                          + $"blend_width: {F(b.BlendWidth)}, material: \"{matId}\" }}");
        }
        sb.AppendLine($"        material: \"{fallback}\"");
        sb.AppendLine();
    }

    public static string F(float v) => v.ToString("0.000", Inv);
    public static string Vec3(Vector3 v) => $"[{F(v.X)}, {F(v.Y)}, {F(v.Z)}]";
}
