using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Numerics;
using System.Text;
using TerrainGen.Splatting;

namespace TerrainGen.Output;

/// <summary>
/// Emits the importable terrain template YAML: <c>materials</c>, <c>templates</c>,
/// and (when water is present) a <c>water</c> material plus a water surface mesh
/// child. Mesh paths are emitted relative to the <c>scenes/</c> root, which is
/// where master scenes live and where the engine resolves <c>type: mesh</c>
/// paths from (see <c>SceneLoader.cs:1597-1600</c>).
/// </summary>
public static class YamlEmitter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Write(GenerationConfig cfg, TerrainMeshBundle bundle, IEnumerable<string> writtenObjs, string templateName, string materialPrefix, string objRelativeDirFromScenesRoot)
    {
        var sb = new StringBuilder();
        EmitHeader(sb, cfg);
        EmitMaterials(sb, cfg, bundle, materialPrefix);
        EmitTemplate(sb, cfg, bundle, templateName, materialPrefix, objRelativeDirFromScenesRoot, writtenObjs);
        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb, GenerationConfig cfg)
    {
        sb.AppendLine("# 3D-Ray terrain template — generated by TerrainGen");
        sb.AppendLine($"# type={cfg.Type.ToString().ToLowerInvariant()} include={DescribeInclude(cfg)} season={cfg.Season.ToString().ToLowerInvariant()}");
        sb.AppendLine($"# size={F(cfg.Size)} resolution={cfg.Resolution} seed={cfg.Seed} style={cfg.Style.ToString().ToLowerInvariant()}");
        sb.AppendLine("#");
        sb.AppendLine("# To use in a scene, place the scene under scenes/ and import this file:");
        sb.AppendLine("#   imports:");
        sb.AppendLine("#     - path: \"libraries/terrain/" + cfg.Name + ".yaml\"");
        sb.AppendLine("#   entities:");
        sb.AppendLine("#     - { type: \"instance\", template: \"<template-name>\", translate: [0, 0, 0] }");
        sb.AppendLine();
    }

    private static string DescribeInclude(GenerationConfig cfg)
    {
        if (cfg.Include == WaterFeatures.None) return "(none)";
        var parts = new List<string>();
        if (cfg.HasFlag(WaterFeatures.Fiumi)) parts.Add("fiumi");
        if (cfg.HasFlag(WaterFeatures.Laghi)) parts.Add("laghi");
        if (cfg.HasFlag(WaterFeatures.Mare))  parts.Add("mare");
        if (cfg.HasFlag(WaterFeatures.Isole)) parts.Add("isole");
        return string.Join(",", parts);
    }

    private static void EmitMaterials(StringBuilder sb, GenerationConfig cfg, TerrainMeshBundle bundle, string prefix)
    {
        sb.AppendLine("materials:");
        foreach (var (stratum, mesh) in bundle.Land)
        {
            if (mesh.Faces.Count == 0) continue;
            EmitStratumMaterial(sb, stratum, cfg, $"{prefix}_{stratum.Suffix()}");
        }
        if (bundle.WaterSurface != null && bundle.WaterSurface.Faces.Count > 0)
            EmitWaterMaterial(sb, $"{prefix}_water");
    }

    private static void EmitStratumMaterial(StringBuilder sb, Stratum stratum, GenerationConfig cfg, string id)
    {
        var p = PaletteLibrary.ForStratum(stratum, cfg.Season, cfg.Style);
        sb.AppendLine($"  - id: \"{id}\"");
        sb.AppendLine($"    type: \"{p.Type}\"");
        if (stratum == Stratum.Snow)
        {
            // Snow uses a flat color + Disney subsurface, no procedural texture.
            sb.AppendLine($"    color: {Vec3(p.ColorA)}");
            sb.AppendLine($"    roughness: {F(p.Roughness)}");
            sb.AppendLine($"    metallic: 0.000");
            sb.AppendLine($"    specular: {F(p.Specular)}");
            sb.AppendLine($"    subsurface: {F(p.Subsurface)}");
            sb.AppendLine($"    subsurface_color: {Vec3(p.SubsurfaceColor)}");
        }
        else
        {
            sb.AppendLine($"    texture:");
            sb.AppendLine($"      type: \"noise\"");
            sb.AppendLine($"      scale: {F(p.NoiseScale)}");
            sb.AppendLine($"      noise_strength: {F(p.NoiseStrength)}");
            sb.AppendLine($"      colors: [{Vec3(p.ColorA)}, {Vec3(p.ColorB)}]");
            sb.AppendLine($"      randomize_offset: true");
            if (p.Type == "disney")
            {
                sb.AppendLine($"    roughness: {F(p.Roughness)}");
                sb.AppendLine($"    metallic: 0.000");
                sb.AppendLine($"    specular: {F(p.Specular)}");
            }
        }
        sb.AppendLine();
    }

    private static void EmitWaterMaterial(StringBuilder sb, string id)
    {
        // Tunable but a solid default: clear water, slight teal absorption.
        sb.AppendLine($"  - id: \"{id}\"");
        sb.AppendLine($"    type: \"disney\"");
        sb.AppendLine($"    color: [0.850, 0.920, 0.950]");
        sb.AppendLine($"    roughness: 0.080");
        sb.AppendLine($"    metallic: 0.000");
        sb.AppendLine($"    specular: 0.500");
        sb.AppendLine($"    spec_trans: 1.000");
        sb.AppendLine($"    ior: 1.330");
        sb.AppendLine($"    transmission_color: [0.300, 0.550, 0.650]");
        sb.AppendLine($"    transmission_depth: 4.000");
        sb.AppendLine();
    }

    private static void EmitTemplate(StringBuilder sb, GenerationConfig cfg, TerrainMeshBundle bundle,
        string templateName, string materialPrefix, string objRelDir, IEnumerable<string> writtenObjs)
    {
        sb.AppendLine("templates:");
        sb.AppendLine($"  - name: \"{templateName}\"");
        sb.AppendLine("    children:");
        foreach (var (stratum, mesh) in bundle.Land)
        {
            if (mesh.Faces.Count == 0) continue;
            string objName = $"{cfg.Name}-{stratum.Suffix()}.obj";
            sb.AppendLine($"      - type: \"mesh\"");
            sb.AppendLine($"        path: \"{Combine(objRelDir, objName)}\"");
            sb.AppendLine($"        material: \"{materialPrefix}_{stratum.Suffix()}\"");
        }
        if (bundle.WaterSurface != null && bundle.WaterSurface.Faces.Count > 0)
        {
            string objName = $"{cfg.Name}-water.obj";
            sb.AppendLine($"      - type: \"mesh\"");
            sb.AppendLine($"        path: \"{Combine(objRelDir, objName)}\"");
            sb.AppendLine($"        material: \"{materialPrefix}_water\"");
        }
        sb.AppendLine();
    }

    private static string Combine(string a, string b) => string.IsNullOrEmpty(a) ? b : $"{a}/{b}";

    public static string F(float v) => v.ToString("0.000", Inv);
    public static string Vec3(Vector3 v) => $"[{F(v.X)}, {F(v.Y)}, {F(v.Z)}]";
}
