using System;
using System.Numerics;

namespace TerrainGen.Heightmap;

/// <summary>
/// Classic Ken Perlin "improved noise" (2002) in 3D plus an fBm helper.
///
/// Self-contained, no external dependencies. Deterministic given a seed.
/// Verbatim port of <c>src/RayTracer/Volumetrics/PerlinNoise.cs</c> so the noise
/// generated by this tool matches what the engine itself uses for procedural
/// volumetrics — useful when authoring scenes that combine a generated terrain
/// with procedural fog of the same character.
/// </summary>
public sealed class PerlinNoise
{
    private readonly int[] _p = new int[512];

    public PerlinNoise(int seed = 0)
    {
        var perm = new int[256];
        for (int i = 0; i < 256; i++) perm[i] = i;
        var rng = new Random(seed);
        for (int i = 255; i > 0; i--)
        {
            int j = rng.Next(i + 1);
            (perm[i], perm[j]) = (perm[j], perm[i]);
        }
        for (int i = 0; i < 512; i++) _p[i] = perm[i & 255];
    }

    public float Noise(float x, float y, float z)
    {
        int X = (int)MathF.Floor(x) & 255;
        int Y = (int)MathF.Floor(y) & 255;
        int Z = (int)MathF.Floor(z) & 255;

        x -= MathF.Floor(x);
        y -= MathF.Floor(y);
        z -= MathF.Floor(z);

        float u = Fade(x);
        float v = Fade(y);
        float w = Fade(z);

        int A = _p[X]     + Y, AA = _p[A] + Z, AB = _p[A + 1] + Z;
        int B = _p[X + 1] + Y, BA = _p[B] + Z, BB = _p[B + 1] + Z;

        return Lerp(w,
                    Lerp(v, Lerp(u, Grad(_p[AA    ], x,      y,      z),
                                    Grad(_p[BA    ], x - 1f, y,      z)),
                            Lerp(u, Grad(_p[AB    ], x,      y - 1f, z),
                                    Grad(_p[BB    ], x - 1f, y - 1f, z))),
                    Lerp(v, Lerp(u, Grad(_p[AA + 1], x,      y,      z - 1f),
                                    Grad(_p[BA + 1], x - 1f, y,      z - 1f)),
                            Lerp(u, Grad(_p[AB + 1], x,      y - 1f, z - 1f),
                                    Grad(_p[BB + 1], x - 1f, y - 1f, z - 1f))));
    }

    public float Noise(Vector2 p) => Noise(p.X, 0f, p.Y);
    public float Noise(Vector3 p) => Noise(p.X, p.Y, p.Z);

    public float NoiseUnit(Vector3 p) => 0.5f * (Noise(p.X, p.Y, p.Z) + 1f);

    public float Fbm(Vector3 p, int octaves, float lacunarity = 2f, float gain = 0.5f)
    {
        float sum = 0f, amp = 1f, freq = 1f, ampSum = 0f;
        int oct = Math.Max(1, octaves);
        for (int i = 0; i < oct; i++)
        {
            sum += amp * Noise(p.X * freq, p.Y * freq, p.Z * freq);
            ampSum += amp;
            amp *= gain;
            freq *= lacunarity;
        }
        return sum / MathF.Max(ampSum, 1e-6f);
    }

    public float FbmUnit(Vector3 p, int octaves, float lacunarity = 2f, float gain = 0.5f)
        => 0.5f * (Fbm(p, octaves, lacunarity, gain) + 1f);

    /// <summary>Ridged multifractal: 1 - |fbm|, raises sharp ridges and flat valleys.</summary>
    public float Ridged(Vector3 p, int octaves, float lacunarity = 2f, float gain = 0.5f)
    {
        float sum = 0f, amp = 1f, freq = 1f, ampSum = 0f;
        int oct = Math.Max(1, octaves);
        for (int i = 0; i < oct; i++)
        {
            float n = Noise(p.X * freq, p.Y * freq, p.Z * freq);
            sum += amp * (1f - MathF.Abs(n));
            ampSum += amp;
            amp *= gain;
            freq *= lacunarity;
        }
        return sum / MathF.Max(ampSum, 1e-6f);
    }

    private static float Fade(float t) => t * t * t * (t * (t * 6f - 15f) + 10f);
    private static float Lerp(float t, float a, float b) => a + t * (b - a);

    private static float Grad(int hash, float x, float y, float z)
    {
        int h = hash & 15;
        float u = h < 8 ? x : y;
        float v = h < 4 ? y : (h == 12 || h == 14 ? x : z);
        return ((h & 1) == 0 ? u : -u) + ((h & 2) == 0 ? v : -v);
    }
}
