using System;
using System.IO;
using System.Text;
using System.Globalization;

namespace ChessGen
{
    // Generates scenes/chess.yaml: a Staunton chess set laid out in the Italian Game
    // (Giuoco Piano) opening position after 1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5, using
    // templates + instances. Material + lighting are tuned for a "tournament catalogue"
    // look: boxwood pieces vs. ebony pieces on a maple/walnut board, soft 3-point
    // studio lighting with a warm area key from a window direction.
    //
    // Coordinate system:
    //   file a..h -> x = (file - 3.5), so x ∈ {-3.5, -2.5, ..., 3.5}
    //   rank 1..8 -> z = (rank - 4.5), so z ∈ {-3.5, -2.5, ..., 3.5}
    //   White back rank at z = -3.5, Black back rank at z = 3.5.
    class Program
    {
        static void Main(string[] args)
        {
            var sb = new StringBuilder();

            EmitHeader(sb);
            EmitWorld(sb);
            EmitCameras(sb);
            EmitMaterials(sb);
            EmitLights(sb);
            EmitTemplates(sb);
            EmitEntities(sb);

            string outPath = ResolveOutputPath();
            File.WriteAllText(outPath, sb.ToString());
            Console.WriteLine($"Chess scene generated: {outPath}");
        }

        // Walk up from the running binary until we find the repo root (identified by
        // the presence of a `scenes/` directory), then point at scenes/chess.yaml.
        // Robust whether `dotnet run` is invoked from the repo root or from the
        // project directory.
        static string ResolveOutputPath()
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, "scenes")))
                dir = dir.Parent;
            if (dir == null)
                throw new DirectoryNotFoundException("Could not locate repo root (no 'scenes/' directory found above the binary).");
            return Path.Combine(dir.FullName, "scenes", "chess.yaml");
        }

        // ---------- formatting helpers ----------

        static string VFmt(float v) => v.ToString("0.000", CultureInfo.InvariantCulture);

        static string Vec3(float x, float y, float z) => $"[{VFmt(x)}, {VFmt(y)}, {VFmt(z)}]";

        // ---------- sections ----------

        static void EmitHeader(StringBuilder sb)
        {
            sb.AppendLine("# Ray-Tracing Scene - Staunton Chess Set, Italian Game opening");
            sb.AppendLine("# Procedurally generated by src/Tools/ChessGen.");
            sb.AppendLine("# Position: 1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 (Giuoco Piano, 3 moves per side).");
            sb.AppendLine("# Pieces are emitted as a template per piece type + one instance per board");
            sb.AppendLine("# square. Edit ChessGen/Program.cs to regenerate this file.");
            sb.AppendLine();
        }

        static void EmitWorld(StringBuilder sb)
        {
            sb.AppendLine("world:");
            sb.AppendLine("  # Daytime studio: sky gradient with a warm sun disk that aligns with the");
            sb.AppendLine("  # area key light below. Moderate ambient fills shadows without flattening.");
            sb.AppendLine("  ambient_light: [0.10, 0.10, 0.11]");
            sb.AppendLine("  sky:");
            sb.AppendLine("    type: \"gradient\"");
            sb.AppendLine("    zenith_color:  [0.22, 0.38, 0.70]");
            sb.AppendLine("    horizon_color: [0.75, 0.82, 0.92]");
            sb.AppendLine("    ground_color:  [0.18, 0.15, 0.10]");
            sb.AppendLine("    sun:");
            sb.AppendLine("      direction: [-0.55, -0.78, -0.30]");
            sb.AppendLine("      color: [1.0, 0.96, 0.88]");
            sb.AppendLine("      intensity: 10.0");
            sb.AppendLine("      size: 2.0");
            sb.AppendLine("      falloff: 48.0");
            sb.AppendLine("  ground:");
            sb.AppendLine("    type: \"infinite_plane\"");
            sb.AppendLine("    material: \"table_wood\"");
            sb.AppendLine("    y: -0.20");
            sb.AppendLine();
        }

        static void EmitCameras(StringBuilder sb)
        {
            sb.AppendLine("cameras:");
            sb.AppendLine("  - name:       classica        # Prospettiva Classica");
            sb.AppendLine("    position:   [0, 5, -8]");
            sb.AppendLine("    look_at:    [0, 0, 0]");
            sb.AppendLine("    fov:        45");
            sb.AppendLine("    aperture:   0.1");
            sb.AppendLine("    focal_dist: 12.0");
            sb.AppendLine();
            sb.AppendLine("  - name:       macro           # Dettaglio sui Pezzi Centrali");
            sb.AppendLine("    position:   [1.5, 1.2, -4]");
            sb.AppendLine("    look_at:    [0, 0.8, 0]");
            sb.AppendLine("    fov:        25.0");
            sb.AppendLine("    aperture:   0.2");
            sb.AppendLine("    focal_dist: 4.25");
            sb.AppendLine();
            sb.AppendLine("  - name:       hero            # Angolo Basso e Imponente");
            sb.AppendLine("    position:   [0.0, 0.5, -6.5]");
            sb.AppendLine("    look_at:    [0.0, 1.0, 0.5]");
            sb.AppendLine("    fov:        55.0");
            sb.AppendLine("    aperture:   0.1");
            sb.AppendLine("    focal_dist: 7.0");
            sb.AppendLine();
            sb.AppendLine("  - name:       zenitale        # Vista dall'alto tattica");
            sb.AppendLine("    position:   [0.0, 12.0, 0.01]");
            sb.AppendLine("    look_at:    [0.0, 0.0, 0.0]");
            sb.AppendLine("    fov:        35.0");
            sb.AppendLine("    aperture:   0.0");
            sb.AppendLine("    focal_dist: 12.0");
            sb.AppendLine();
            sb.AppendLine("  - name:       dutch           # Dinamica e Inclinata");
            sb.AppendLine("    position:   [6.0, 4.0, -6.0]");
            sb.AppendLine("    look_at:    [0.0, 0.5, 0.0]");
            sb.AppendLine("    fov:        40.0");
            sb.AppendLine("    aperture:   0.1");
            sb.AppendLine("    focal_dist: 8.5");
            sb.AppendLine();
            sb.AppendLine("  - name:       pawns_eye       # Ad altezza pedina, Bokeh estremo");
            sb.AppendLine("    position:   [0.0, 0.4, -3.5]");
            sb.AppendLine("    look_at:    [0.0, 0.6, 2.0]");
            sb.AppendLine("    fov:        70.0");
            sb.AppendLine("    aperture:   0.3");
            sb.AppendLine("    focal_dist: 3.5");
            sb.AppendLine();
        }

        static void EmitMaterials(StringBuilder sb)
        {
            sb.AppendLine("materials:");

            // Ground (infinite plane): medium walnut with visible grain.
            sb.AppendLine("  - id: \"table_wood\"");
            sb.AppendLine("    type: \"lambertian\"");
            sb.AppendLine("    texture:");
            sb.AppendLine("      type: \"wood\"");
            sb.AppendLine("      scale: 6.0");
            sb.AppendLine("      noise_strength: 2.8");
            sb.AppendLine("      colors: [[0.28, 0.16, 0.08], [0.15, 0.08, 0.04]]");
            sb.AppendLine("      randomize_offset: true");
            sb.AppendLine("      rotation: [90, 0, 0]");
            sb.AppendLine();

            // Board squares: maple + walnut checker.
            sb.AppendLine("  - id: \"board_checker\"");
            sb.AppendLine("    type: \"lambertian\"");
            sb.AppendLine("    texture:");
            sb.AppendLine("      type: \"checker\"");
            sb.AppendLine("      scale: 0.125");
            sb.AppendLine("      colors: [[0.82, 0.70, 0.48], [0.20, 0.11, 0.06]]");
            sb.AppendLine();

            // Board border: dark mahogany with tighter grain.
            sb.AppendLine("  - id: \"board_border\"");
            sb.AppendLine("    type: \"lambertian\"");
            sb.AppendLine("    texture:");
            sb.AppendLine("      type: \"wood\"");
            sb.AppendLine("      scale: 20.0");
            sb.AppendLine("      noise_strength: 3.0");
            sb.AppendLine("      colors: [[0.22, 0.09, 0.05], [0.09, 0.04, 0.02]]");
            sb.AppendLine();

            // White pieces: lacquered boxwood (ivory-cream, warm).
            sb.AppendLine("  - id: \"piece_white\"");
            sb.AppendLine("    type: \"disney\"");
            sb.AppendLine("    color: [0.92, 0.84, 0.68]");
            sb.AppendLine("    metallic: 0.0");
            sb.AppendLine("    roughness: 0.28");
            sb.AppendLine("    specular: 0.5");
            sb.AppendLine("    clearcoat: 0.5");
            sb.AppendLine("    clearcoat_gloss: 0.85");
            sb.AppendLine();

            // Black pieces: lacquered ebony (deep black, high gloss clearcoat).
            sb.AppendLine("  - id: \"piece_black\"");
            sb.AppendLine("    type: \"disney\"");
            sb.AppendLine("    color: [0.05, 0.04, 0.035]");
            sb.AppendLine("    metallic: 0.0");
            sb.AppendLine("    roughness: 0.22");
            sb.AppendLine("    specular: 0.5");
            sb.AppendLine("    clearcoat: 0.6");
            sb.AppendLine("    clearcoat_gloss: 0.90");
            sb.AppendLine();
        }

        static void EmitLights(StringBuilder sb)
        {
            sb.AppendLine("lights:");
            sb.AppendLine("  # KEY: wide warm area light high-left (window), aligned with sky sun.");
            sb.AppendLine("  - type: \"area\"");
            sb.AppendLine("    corner: [-5.0, 8.0, -4.0]");
            sb.AppendLine("    u: [3.5, 0.0, 0.0]");
            sb.AppendLine("    v: [0.0, 0.0, 3.5]");
            sb.AppendLine("    color: [1.0, 0.95, 0.85]");
            sb.AppendLine("    intensity: 55.0");
            sb.AppendLine("    shadow_samples: 16");
            sb.AppendLine();
            sb.AppendLine("  # FILL: cool sphere light from camera-right, softens key-side shadows.");
            sb.AppendLine("  - type: \"sphere\"");
            sb.AppendLine("    position: [4.5, 4.0, -2.5]");
            sb.AppendLine("    radius: 0.8");
            sb.AppendLine("    color: [0.80, 0.86, 1.0]");
            sb.AppendLine("    intensity: 22.0");
            sb.AppendLine("    shadow_samples: 12");
            sb.AppendLine();
            sb.AppendLine("  # RIM/BACK: warm sphere light behind board, separates pieces from background.");
            sb.AppendLine("  - type: \"sphere\"");
            sb.AppendLine("    position: [0.0, 5.5, 5.5]");
            sb.AppendLine("    radius: 0.6");
            sb.AppendLine("    color: [1.0, 0.92, 0.80]");
            sb.AppendLine("    intensity: 30.0");
            sb.AppendLine("    shadow_samples: 12");
            sb.AppendLine();
        }

        // ---------- templates ----------

        static void EmitTemplates(StringBuilder sb)
        {
            sb.AppendLine("templates:");
            EmitTemplate(sb, "pawn",         BuildPawn);
            EmitTemplate(sb, "rook",         BuildRook);
            EmitTemplate(sb, "bishop",       BuildBishop);
            EmitTemplate(sb, "queen",        BuildQueen);
            EmitTemplate(sb, "king",         BuildKing);
            EmitTemplate(sb, "knight_white", sb2 => BuildKnight(sb2, +1));
            EmitTemplate(sb, "knight_black", sb2 => BuildKnight(sb2, -1));
        }

        static void EmitTemplate(StringBuilder sb, string name, Action<StringBuilder> buildChildren)
        {
            sb.AppendLine($"  - name: \"{name}\"");
            sb.AppendLine("    children:");
            buildChildren(sb);
            sb.AppendLine();
        }

        // Primitive emitters for template children: no name, no material (inherited),
        // always in local coordinates around the piece origin at (0,0,0).

        static void ChildCyl(StringBuilder sb, float y, float radius, float height)
        {
            sb.AppendLine("      - type: \"cylinder\"");
            sb.AppendLine($"        center: {Vec3(0, y, 0)}");
            sb.AppendLine($"        radius: {VFmt(radius)}");
            sb.AppendLine($"        height: {VFmt(height)}");
        }

        static void ChildSph(StringBuilder sb, float y, float radius) =>
            ChildSphAt(sb, 0, y, 0, radius);

        static void ChildSphAt(StringBuilder sb, float x, float y, float z, float radius)
        {
            sb.AppendLine("      - type: \"sphere\"");
            sb.AppendLine($"        center: {Vec3(x, y, z)}");
            sb.AppendLine($"        radius: {VFmt(radius)}");
        }

        // Box is centred on its `translate`; (dx, dy, dz) are HALF extents.
        static void ChildBox(StringBuilder sb, float x, float y, float z, float dx, float dy, float dz)
        {
            sb.AppendLine("      - type: \"box\"");
            sb.AppendLine($"        scale: {Vec3(dx * 2, dy * 2, dz * 2)}");
            sb.AppendLine($"        translate: {Vec3(x, y, z)}");
        }

        // ---------- piece geometry (local coords, base at y=0) ----------

        static void BuildPawn(StringBuilder sb)
        {
            ChildCyl(sb, 0.00f, 0.35f, 0.10f);   // base1
            ChildCyl(sb, 0.10f, 0.25f, 0.05f);   // base2
            ChildCyl(sb, 0.15f, 0.16f, 0.40f);   // stem
            ChildCyl(sb, 0.55f, 0.20f, 0.05f);   // collar
            ChildSph(sb, 0.78f, 0.22f);          // head
        }

        static void BuildRook(StringBuilder sb)
        {
            ChildCyl(sb, 0.00f, 0.40f, 0.15f);   // base1
            ChildCyl(sb, 0.15f, 0.30f, 0.05f);   // base2
            ChildCyl(sb, 0.20f, 0.24f, 0.60f);   // stem
            ChildCyl(sb, 0.80f, 0.34f, 0.20f);   // head ring
            // 4 crenellations on the corners of the top ring
            ChildBox(sb, -0.22f, 1.05f, -0.22f, 0.08f, 0.05f, 0.08f);
            ChildBox(sb,  0.22f, 1.05f, -0.22f, 0.08f, 0.05f, 0.08f);
            ChildBox(sb, -0.22f, 1.05f,  0.22f, 0.08f, 0.05f, 0.08f);
            ChildBox(sb,  0.22f, 1.05f,  0.22f, 0.08f, 0.05f, 0.08f);
        }

        static void BuildBishop(StringBuilder sb)
        {
            ChildCyl(sb, 0.00f, 0.35f, 0.10f);   // base1
            ChildCyl(sb, 0.10f, 0.25f, 0.05f);   // base2
            ChildCyl(sb, 0.15f, 0.15f, 0.55f);   // stem
            ChildCyl(sb, 0.70f, 0.22f, 0.05f);   // collar
            ChildSph(sb, 0.92f, 0.22f);          // mitre lower
            ChildSph(sb, 1.08f, 0.14f);          // mitre upper
            ChildSph(sb, 1.28f, 0.06f);          // top ball
        }

        static void BuildQueen(StringBuilder sb)
        {
            ChildCyl(sb, 0.00f, 0.40f, 0.10f);   // base1
            ChildCyl(sb, 0.10f, 0.30f, 0.05f);   // base2
            ChildCyl(sb, 0.15f, 0.20f, 0.80f);   // stem
            ChildCyl(sb, 0.95f, 0.30f, 0.05f);   // collar
            ChildSph(sb, 1.15f, 0.20f);          // head
            // 8 crown points
            for (int i = 0; i < 8; i++)
            {
                double ang = i * Math.PI / 4.0;
                float px = (float)Math.Cos(ang) * 0.20f;
                float pz = (float)Math.Sin(ang) * 0.20f;
                ChildSphAt(sb, px, 1.30f, pz, 0.06f);
            }
            ChildSph(sb, 1.42f, 0.05f);          // centre pearl
        }

        static void BuildKing(StringBuilder sb)
        {
            ChildCyl(sb, 0.00f, 0.40f, 0.10f);   // base1
            ChildCyl(sb, 0.10f, 0.30f, 0.08f);   // base2
            ChildCyl(sb, 0.18f, 0.22f, 0.85f);   // stem
            ChildCyl(sb, 1.03f, 0.34f, 0.05f);   // collar
            ChildSph(sb, 1.25f, 0.24f);          // head
            ChildSph(sb, 1.45f, 0.04f);          // cross base pearl
            // Latin cross (vertical + horizontal bars)
            ChildBox(sb, 0.00f, 1.58f, 0.00f, 0.03f, 0.12f, 0.03f);
            ChildBox(sb, 0.00f, 1.60f, 0.00f, 0.08f, 0.03f, 0.03f);
        }

        // Knight faces towards lookDir * +Z. White pieces (lookDir = +1) look at Black
        // (positive Z); Black (-1) looks back at White (negative Z).
        static void BuildKnight(StringBuilder sb, int lookDir)
        {
            ChildCyl(sb, 0.00f, 0.35f, 0.10f);   // base1
            ChildCyl(sb, 0.10f, 0.25f, 0.05f);   // base2
            ChildCyl(sb, 0.15f, 0.22f, 0.40f);   // stem
            ChildSph(sb, 0.65f, 0.25f);          // chest
            ChildSphAt(sb, 0.00f, 0.90f, lookDir * 0.10f, 0.22f);  // head
            ChildBox(sb, 0.00f, 0.85f, lookDir * 0.25f, 0.15f, 0.10f, 0.18f);  // snout
            ChildSphAt(sb, -0.10f, 1.05f, -lookDir * 0.05f, 0.06f); // ear left
            ChildSphAt(sb,  0.10f, 1.05f, -lookDir * 0.05f, 0.06f); // ear right
        }

        // ---------- entities (board + 32 piece instances) ----------

        // Italian Game (Giuoco Piano) after 1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5.
        // Each instance: (name, template, file x, rank z, material).
        record Inst(string Name, string Template, float X, float Z, string Mat);

        static readonly Inst[] Pieces = new[]
        {
            // White back rank — untouched: Ra1, Nb1, Bc1, Qd1, Ke1, Rh1
            new Inst("wr_a1", "rook",         -3.5f, -3.5f, "piece_white"),
            new Inst("wn_b1", "knight_white", -2.5f, -3.5f, "piece_white"),
            new Inst("wb_c1", "bishop",       -1.5f, -3.5f, "piece_white"),
            new Inst("wq_d1", "queen",        -0.5f, -3.5f, "piece_white"),
            new Inst("wk_e1", "king",          0.5f, -3.5f, "piece_white"),
            new Inst("wr_h1", "rook",          3.5f, -3.5f, "piece_white"),
            // White developed pieces: Bc4 (from f1), Nf3 (from g1)
            new Inst("wb_c4", "bishop",       -1.5f, -0.5f, "piece_white"),
            new Inst("wn_f3", "knight_white",  1.5f, -1.5f, "piece_white"),
            // White pawns on rank 2, except e-pawn now on e4
            new Inst("wp_a2", "pawn",         -3.5f, -2.5f, "piece_white"),
            new Inst("wp_b2", "pawn",         -2.5f, -2.5f, "piece_white"),
            new Inst("wp_c2", "pawn",         -1.5f, -2.5f, "piece_white"),
            new Inst("wp_d2", "pawn",         -0.5f, -2.5f, "piece_white"),
            new Inst("wp_f2", "pawn",          1.5f, -2.5f, "piece_white"),
            new Inst("wp_g2", "pawn",          2.5f, -2.5f, "piece_white"),
            new Inst("wp_h2", "pawn",          3.5f, -2.5f, "piece_white"),
            new Inst("wp_e4", "pawn",          0.5f, -0.5f, "piece_white"),

            // Black back rank — untouched: Ra8, Bc8, Qd8, Ke8, Ng8, Rh8 (Nb8 left)
            new Inst("br_a8", "rook",         -3.5f,  3.5f, "piece_black"),
            new Inst("bb_c8", "bishop",       -1.5f,  3.5f, "piece_black"),
            new Inst("bq_d8", "queen",        -0.5f,  3.5f, "piece_black"),
            new Inst("bk_e8", "king",          0.5f,  3.5f, "piece_black"),
            new Inst("bn_g8", "knight_black",  2.5f,  3.5f, "piece_black"),
            new Inst("br_h8", "rook",          3.5f,  3.5f, "piece_black"),
            // Black developed pieces: Nc6 (from b8), Bc5 (from f8)
            new Inst("bn_c6", "knight_black", -1.5f,  1.5f, "piece_black"),
            new Inst("bb_c5", "bishop",       -1.5f,  0.5f, "piece_black"),
            // Black pawns on rank 7, except e-pawn now on e5
            new Inst("bp_a7", "pawn",         -3.5f,  2.5f, "piece_black"),
            new Inst("bp_b7", "pawn",         -2.5f,  2.5f, "piece_black"),
            new Inst("bp_c7", "pawn",         -1.5f,  2.5f, "piece_black"),
            new Inst("bp_d7", "pawn",         -0.5f,  2.5f, "piece_black"),
            new Inst("bp_f7", "pawn",          1.5f,  2.5f, "piece_black"),
            new Inst("bp_g7", "pawn",          2.5f,  2.5f, "piece_black"),
            new Inst("bp_h7", "pawn",          3.5f,  2.5f, "piece_black"),
            new Inst("bp_e5", "pawn",          0.5f,  0.5f, "piece_black"),
        };

        static void EmitEntities(StringBuilder sb)
        {
            sb.AppendLine("entities:");
            // Board playing surface
            sb.AppendLine("  - name: \"chessboard_main\"");
            sb.AppendLine("    type: \"box\"");
            sb.AppendLine("    scale: [8.000, 0.100, 8.000]");
            sb.AppendLine("    translate: [0.000, -0.050, 0.000]");
            sb.AppendLine("    material: \"board_checker\"");
            sb.AppendLine();
            // Mahogany border, slightly lower and wider so it peeks out under the playing surface
            sb.AppendLine("  - name: \"border\"");
            sb.AppendLine("    type: \"box\"");
            sb.AppendLine("    scale: [8.600, 0.160, 8.600]");
            sb.AppendLine("    translate: [0.000, -0.090, 0.000]");
            sb.AppendLine("    material: \"board_border\"");
            sb.AppendLine();

            foreach (var p in Pieces)
            {
                sb.AppendLine($"  - name: \"{p.Name}\"");
                sb.AppendLine("    type: \"instance\"");
                sb.AppendLine($"    template: \"{p.Template}\"");
                sb.AppendLine($"    translate: {Vec3(p.X, 0.0f, p.Z)}");
                sb.AppendLine($"    material: \"{p.Mat}\"");
                sb.AppendLine();
            }
        }
    }
}
